export GOPATH="$HOME/go"
export EDITOR="nvim"
export VISUAL="nvim"
export PATH="/usr/local/sbin:$PATH:$GOPATH/bin"
export PROMPT_LEAN_VIMODE=true
export FZF_COMPLETION_TRIGGER=''
export FZF_DEFAULT_COMMAND='rg --files'
export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"
export PATH="/usr/local/opt/icu4c/bin:$PATH"
export PATH="/usr/local/opt/icu4c/sbin:$PATH"
export NVM_DIR="$HOME/.nvm"
export DOTFILES="$HOME/.config"
export ZSH_PLUGINS_DIR="$HOME/.local/share/zsh/plugins"
export TMUX_PLUGINS_DIR="$HOME/.local/share/tmux/plugins"
