# espanso match file

# For a complete introduction, visit the official docs at: https://espanso.org/docs/

# You can use this file to define the base matches (aka snippets)
# that will be available in every application when using espanso.

# Matches are substitution rules: when you type the "trigger" string
# it gets replaced by the "replace" string.
matches:
  # Simple text replacement
  - trigger: ";hey"
    replace: "Hey $|$👋🏼!"
  - trigger: ";hi"
    replace: "Hi $|$👋🏼!"
  - trigger: ";hello"
    replace: "Hello $|$👋🏼!"
  - trigger: ";WDYT"
    replace: "What do you think"
  - trigger: ";in_dev"
    replace: |
      /label ~"flow::in dev" ~"backend::doing" 
      /assign @ajay91
  - trigger: ";in_review"
    replace: |
      /label ~"backend::in-review"
  - trigger: ";close"
    replace: |
      /label ~"flow::done" ~"backend::done"
      /close
  - trigger: ";done"
    replace: |
      /label ~"flow::done" ~"backend::done" 
  - trigger: ";be_done"
    replace: |
      /label ~"backend::done" 
  - trigger: ";now"
    replace: "{{mytime}}"
    vars:
      - name: mytime
        type: date
        params:
          format: "%H:%M"
  - trigger: ";utc_now"
    replace: "{{utctime}}"
    vars:
      - name: utctime
        type: shell
        params:
          cmd: "date -u '+%H:%M'"
  - trigger: ";docs"
    replace: "{{form1.file}}"
    vars:
      - name: files
        type: shell
        params:
          cmd: "find ~/Documents -maxdepth 1"
      - name: form1
        type: form
        params:
          layout: |
            Select file:
            [[file]]
          fields:
            file:
              type: list
              values: "{{files}}"
